version: '2'

services:

  contability:

    build:
      context: .
      dockerfile: app.Dockerfile

    image: rcabarreto/vanhackforum

    container_name: vanhackforum

    environment:
      - NODE_ENV=production
      - DATABASE_HOST=database
      - DATABASE_PORT=3306
      - DATABASE_NAME=vanhackforum
      - DATABASE_USER=root
      - DATABASE_PWD=asdfasdf
      - WAIT_HOSTS=database:3306

    depends_on:
      - database

    networks:
      - forum-network

  webserver:

    build:
      context: .
      dockerfile: nginx.Dockerfile

    image: rcabarreto/proxy

    container_name: web_server

    ports:
      - 80:80
      - 443:443

    volumes:
      - ./public:/usr/share/nginx/html

    networks:
      - forum-network

    links:
      - vanhackforum

  database:

    image: mysql:latest
    container_name: database

    volumes:
      - ./data:/docker-entrypoint-initdb.d
      # - ./data:/var/lib/mysql

    environment:
      MYSQL_DATABASE: vanhackforum
      MYSQL_ROOT_PASSWORD: asdfasdf

    networks:
      - forum-network

  pma:

    image: phpmyadmin/phpmyadmin
    container_name: pma

    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: database
      PMA_USER: root
      PMA_PASSWORD: asdfasdf
      PHP_UPLOAD_MAX_FILESIZE: 1G
      PHP_MAX_INPUT_VARS: 1G

    restart: always

    networks:
      - forum-network

networks:
  forum-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.36.0.1/16
