version: '2'

services:

  forumapp:

    build:
      context: .
      dockerfile: app.Dockerfile

    image: rcabarreto/forumapp

    container_name: simpleforum_app

    environment:
      - NODE_ENV=production
      - DATABASE_HOST=database
      - DATABASE_PORT=3306
      - DATABASE_NAME=forumapp
      - DATABASE_USER=root
      - DATABASE_PWD=asdfasdf
      - WAIT_HOSTS=database:3306

    depends_on:
      - database

    networks:
      - forum-network

  webserver:

    build:
      context: .
      dockerfile: nginx.Dockerfile

    image: rcabarreto/proxy

    container_name: simpleforum_web_server

    ports:
      - 80:80
      - 443:443

    volumes:
      - ./public:/usr/share/nginx/html

    networks:
      - forum-network

    links:
      - forumapp

  database:

    image: mysql:5.7
    container_name: simpleforum_database

    volumes:
      - ./data:/docker-entrypoint-initdb.d
      # - ./data:/var/lib/mysql

    environment:
      MYSQL_DATABASE: forumapp
      MYSQL_ROOT_PASSWORD: asdfasdf

    networks:
      - forum-network

  pma:

    image: phpmyadmin/phpmyadmin
    container_name: simpleforum_pma

    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: database
      PMA_USER: root
      PMA_PASSWORD: asdfasdf
      PHP_UPLOAD_MAX_FILESIZE: 1G
      PHP_MAX_INPUT_VARS: 1G

    restart: always

    networks:
      - forum-network

networks:
  forum-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.36.0.1/16
